### PR TITLE
add slides from 2020 meeting in Tromso

### PR DESCRIPTION
**Pull request by pdurbin**
The slides at http://talks.bertuch.name/dataverse-k8s-20200124/ are great! They do such a good job introducing the project and explaining the context that I think they should go in the README.

@poikilotherm knows this but they come from https://site.uit.no/dataverseno/european-dataverse-workshop-2020/

### CODE REVIEW

**Comment by 4tikhonov** [comment]
@pdurbin, we're going to publish all presentations from the meeting in Tromso, probably it's going to happen next week.

**Comment by pdurbin** [comment]
@4tikhonov fantastic! Oh, at that reminds me, I love how I was able to add the "Dataverse in the European Open Science Cloud" talk ( https://www.youtube.com/watch?v=vAPpKuDQUDY ) you and @philippconzett gave at #dataverse2019 to https://dataverse.org/dataversetv because someone recorded it with a phone! More of that, please. :smile:

**Comment by poikilotherm** [comment]
@pdurbin I'd be happy to include this talk within the guide or similar places, but then I would remove the FZJ branding. Is there a branding from GDCC or similar that I could apply instead?

**Comment by pdurbin** [comment]
@poikilotherm sure, maybe you could use the logo below from https://github.com/GlobalDataverseCommunityConsortium



If anyone knows where the SVG version is, please let me know!

**Comment by poikilotherm** [comment]
Done as part of #207

**Pull request closed without merging**
